spring:
  jpa:
    show-sql: true  
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/fornecedor?useSSL=false&serverTimezone=UTC
